name = "morphdrawer-pwa"
main = "dist/index.html"
compatibility_date = "2024-12-01"

[build]
command = "pnpm run deploy:morphdrawer"
cwd = "./../../"
watch_paths = ["artifacts/morphdrawer/src/**/*"]

[build.upload]
format = "modules"

[env.production]
route = "example.com/*"
zone_name = "example.com"

[[rules]]
type = "CompiledContentType"
globs = ["**/*.woff", "**/*.woff2", "**/*.ttf", "**/*.otf"]
fallthrough = true

[[rules]]
type = "CompiledContentType"
globs = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.svg", "**/*.webp"]
fallthrough = true
